version: 2

sources:
  - name: source
    description: raw data that loads into the bronze layer
    database: bronze
    schema: default
    tables:
      - name: sales
        description: Raw data that loads into the bronze layer